name: Deploy To AWS

on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t soyalper/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true soyalper/docker-react npm test